resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource

resources:
- name: download-package
  type: artifactory
  source:
    endpoint: http://artifactoryhostname:8081/artifactory
    repository: "/Repository" #example: /chocolatey
    regex: "mypackage.(?<version>.*).extension" #example Firefox.(?<version>.*).nukpkg
    user: admin
    password: password
    skip_ssl_verification: true

jobs:
- name: get
  plan:
  - get: download-package